### PR TITLE
Parameter tuning

### PR DESCRIPTION
**Pull request by watakandai**
Tuned Parameters. 

traj
tuning

### CODE REVIEW

**Comment by erdalpekel** [comment]
Hi @peasant98 & @watakandai 

I forgot to have a look at this pull request.
Is this still relevant?

Erdal

**Comment by watakandai** [comment]
I accidentally pushed to the original repo. 
Our team forked your repo and have been working on it.

I tuned the PID parameters of each joint. 
Not for the `effort_controllers` but for the `velocity_controllers`. 
This is because your PID parameters were not complete, so the joint states overshoot and oscillate. 
We fixed the PID parameters so that each joint state converges to the commanded joint position / velocity without any oscillation. 

If you have time, you can experiment with it.
The `yaml` is completed, but all you need is to change the controllers in the `simulation.launch` and `panda.transmission.xacro`. 
And if you would like to somehow merge it into your repo, I can help.

**Comment by chongyi-zheng** [comment]
> Hi @peasant98 & @watakandai
> 
> I forgot to have a look at this pull request.
> Is this still relevant?
> 
> Erdal

Just one question: how did you get the pid parameters in your blog? 

By the way, I tune it by sending a sinusoidal wave to joint_trajectory_controller and reading the joint position. But I found these parameters works for all the panda_joint1 to panda_joint7:

{p: 100,  d: 1, i: 1, i_clamp: 1}

So could you please tell me how to consider a group of parameters to be optimal?

**Comment by chongyi-zheng** [comment]
Hi, there @watakandai! Could you please tell me how did you specify the command send to the follow_joint_trajectory controller? Here is my python sinusoidal wave generator.

```
#!/usr/bin/env python
import rospy
import numpy as np
import actionlib
import trajectory_msgs.msg
import control_msgs.msg



if __name__ == "__main__":
    rospy.init_node('sinusoidal_wave_generator')
    command_topic = rospy.get_param('~command_topic')
    command_joint = rospy.get_param('~command_joint')
    wave_mag = rospy.get_param('~wave_mag')

    publisher = rospy.Publisher(command_topic, trajectory_msgs.msg.JointTrajectory, queue_size=10)
    
    joint_names = ['panda_joint1', 'panda_joint2', 'panda_joint3', 'panda_joint4', 'panda_joint5', 'panda_joint6', 'panda_joint7']
    point = trajectory_msgs.msg.JointTrajectoryPoint()
    point.positions = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    point.velocities = []
    point.accelerations = []
    point.time_from_start = rospy.Duration().from_sec(0.01)

    traj = trajectory_msgs.msg.JointTrajectory()
    traj.header.stamp = rospy.Time.now()
    traj.joint_names = joint_names
    traj.points.append(point)

    r = rospy.Rate(50) # 50 hz
    while not rospy.is_shutdown():
        traj.header.stamp = rospy.Time.now()
        # point.positions[joint_names.index(command_joint)] = wave_mag * np.sin((2 * np.pi / 50) * rospy.Time.now().to_sec())
        point.positions[joint_names.index(command_joint)] = wave_mag * np.sin(rospy.Time.now().to_sec())
        publisher.publish(traj)
        r.sleep()


```


And I found the position in the joint state depends on `time_from_start` parameter: 
If I set it to 1.0, I got



If I set it to 5.0, I got



However, change the pid value didn't affect the joint state at all. Any suggestion?

**Comment by watakandai** [comment]
Hi @YeeCY, just a quick question.

1. Is this in sim or on a real robot?
-> You should use sim

2. What type of controller are you using? or configured in 

https://github.com/erdalpekel/franka_ros/blob/59eafe87c37bb30a65e3432e69caad7f862e917e/franka_description/robots/panda.control.xacro#L8 
and 
https://github.com/erdalpekel/panda_simulation/blob/9b53b0efc4bbdbf21d6d3c250dd06d495e2aae9f/config/panda_control.yaml#L7

If position controller is chosen, PID controller doesn't affect anything.
If it's velocity -> position, effort -> velocity OR effort -> position, then PID values would influence the output values.


> Could you please tell me how did you specify the command send to the follow_joint_trajectory controller? Here is my python sinusoidal wave generator.

For sinusoidal signals, I also created a script like you did and sent it to the command topic. 
Other than the sinusoidal waves, you should also check if the robot is being able to process the "Step Function" smoothly without any overshoot nor oscillation. Please refer to some books on Control Theory to understand deeply. 


The most important question you should ask yourself is, which controller are you using both on the URDF side and when spawning a controller in your launch file. 

Let me know if you have more questions.

**Comment by peasant98** [comment]
Hi @YeeCY, I don't recommend using the Joint Trajectory command here unless you have more than one point. I would recommend using a different controller in this case.

**Comment by watakandai** [comment]
You can choose which controller to use `simulation.launch`

https://github.com/erdalpekel/panda_simulation/blob/9b53b0efc4bbdbf21d6d3c250dd06d495e2aae9f/launch/simulation.launch#L29

and this `panda_arm_controller` is read from `panda_control.yaml` which can be found in `"$(find panda_simulation)/config/panda_control.yaml"` 
https://github.com/erdalpekel/panda_simulation/blob/9b53b0efc4bbdbf21d6d3c250dd06d495e2aae9f/launch/simulation.launch#L25

If you take a look at the file, you notice there is `panda_arm_controller`

```
    panda_arm_controller:
        type: position_controllers/JointTrajectoryController
        joints:
            - panda_joint1
            - panda_joint2
            - panda_joint3
            - panda_joint4
            - panda_joint5
            - panda_joint6
            - panda_joint7

        constraints:
            goal_time: 2.0

        state_publish_rate: 100
```

As @peasant98 has mentioned, we don't recommend using `Joint Trajectory` controller. Although it is easy to use, you need to provide joint position, velocity, and acceleration, which doesn't guarantee the speed at all. 
What you want to do is to add, a velocity controller AND  a position controller like we did, tune it, and send a command to each topic.

**Comment by chongyi-zheng** [comment]
> Hi @YeeCY, just a quick question.
> 
> 1. Is this in sim or on a real robot?
>    -> You should use sim
> 2. What type of controller are you using? or configured in
> 
> https://github.com/erdalpekel/franka_ros/blob/59eafe87c37bb30a65e3432e69caad7f862e917e/franka_description/robots/panda.control.xacro#L8
> and
> https://github.com/erdalpekel/panda_simulation/blob/9b53b0efc4bbdbf21d6d3c250dd06d495e2aae9f/config/panda_control.yaml#L7
> 
> If position controller is chosen, PID controller doesn't affect anything.
> If it's velocity -> position, effort -> velocity OR effort -> position, then PID values would influence the output values.
> 
> > Could you please tell me how did you specify the command send to the follow_joint_trajectory controller? Here is my python sinusoidal wave generator.
> 
> For sinusoidal signals, I also created a script like you did and sent it to the command topic.
> Other than the sinusoidal waves, you should also check if the robot is being able to process the "Step Function" smoothly without any overshoot nor oscillation. Please refer to some books on Control Theory to understand deeply.
> 
> The most important question you should ask yourself is, which controller are you using both on the URDF side and when spawning a controller in your launch file.
> 
> Let me know if you have more questions.

Hi, there. My answer to your questions:

1. I am following the blog mentioned in the README of this repo, so basically it is a Panda in the Gazebo.

2. I am using `hardware_interface/EffortJointInterface` transmission in URDF and configure a `effort_controllers/JointTrajectoryController`

The reason why I want to tune the PID: The author has already provided a group of PID values he tuned and I just want to practice the tuning process on Panda. 

By the way, I have figured out what's wrong on my side: 
1. It is possible and practical to tune a group of PID for a `follow_joint_trajectory` controller like the repo's author did. And tuning the PID for a follow_joint_trajeoctory can let me command the robot with MoveIt directly.
2. Just create a script to generate a sinusoidal wave as I did above and remember to set the `time_from_start` to a small value, basically it was `0.1` in my code.
3. A good visualization tool is important: I recommend `PlotJuggler` https://github.com/facontidavide/PlotJuggler which can plot graphs for messages with complex structure in ROS.
4. I got the two graphs above because I only plotted desired and actual joint positions on them, but you need the `error = desired - actual` to be as small and smooth as possible. Luckily, the panda `follow_joint_trajectory` controller provided those feedback, you can find them in the topic: `${controller_name}/state`. (I don't know if this topic exists for every `follow_joint_trajectory` controller, you may publisher the error yourself otherwise.)
5. Use the dynamic_reconfiguration tool in `rqt_gui` to adjust the `{p, i, d, i_clamp}` value for each actuator. And `{p: 1, i: 0, d:0, i_clamp: 1}` is a good start. You should tune the `p` value first to minimize the error, and then `i` and `d` to smooth the curve. Wikipedia provides some useful suggestions for manually tuning the PIDs: https://en.wikipedia.org/wiki/PID_controller
6. Here is what I got after searching for a group of PIDs that minimize the error below 0.001: 
```
panda_arm_controller:
        type: effort_controllers/JointTrajectoryController
        joints:
            - panda_joint1
            - panda_joint2
            - panda_joint3
            - panda_joint4
            - panda_joint5
            - panda_joint6
            - panda_joint7

        constraints:
            goal_time: 0.6
            stopped_velocity_tolerance: 0.05
            panda_joint1: {trajectory: 0.2, goal: 0.1}
            panda_joint2: {trajectory: 0.2, goal: 0.1}
            panda_joint3: {trajectory: 0.2, goal: 0.1}
            panda_joint4: {trajectory: 0.2, goal: 0.1}
            panda_joint5: {trajectory: 0.2, goal: 0.1}
            panda_joint6: {trajectory: 0.2, goal: 0.1}
            panda_joint7: {trajectory: 0.2, goal: 0.1}

        gains:
            panda_joint1: {p: 10000, d: 500, i: 10, i_clamp: 1}
            panda_joint2: {p: 40000, d: 100, i: 0, i_clamp: 1}
            panda_joint3: {p: 40000, d: 30, i: 0, i_clamp: 1}
            panda_joint4: {p: 25000, d: 50, i: 1, i_clamp: 1}
            panda_joint5: {p: 10000, d: 200, i: 0.2, i_clamp: 1}
            panda_joint6: {p: 15000, d: 100, i: 0, i_clamp: 1}
            panda_joint7: {p: 5000, d: 100, i: 0, i_clamp: 1}
        stop_trajectory_duration: 1.0
        state_publish_rate:  50
        action_monitor_rate: 10
        allow_partial_joints_goal: true

```
7. Since the `follow_joint_trajectory` is very general, you can use this tuning process for other robots like a velocity based controller for UR5

Thanks for your reply @watakandai @peasant98. And I don't know if this tuning method is feasible for real robots, do you guys have any experience?

**Pull request closed without merging**
